# Generated by Django 4.2.13 on 2024-07-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todoitems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitems',
            name='user',
        ),
    ]
