# Generated by Django 4.2.13 on 2024-07-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_remove_todoitems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
